### ISSUE TITLE
Rework Comments UI

### ISSUE THREAD

**Issue by ToucheSir** [fridayideas/daytomato#114]
The current comments UI is somewhat finicky to use due to the cramped space and inability to cancel writing a comment. Moving the viewing of comment data into a different view/dialog would give much needed breathing room and perhaps simplify any view that currently displays comments. This might be a tad hairy, though, as trying to pull comments into a separate view may end up forcing other views to become full-blown activities or dialogs to maintain consistency. Thoughts?

**Comment by james-woo** [comment]
Yea that sounds good to me, I would love to see this

**Comment by ryansama** [comment]
It might be a good idea to remove comments from pins (as it is sufficient for them to be judged only by upvotes/downvotes), but keep it on trips. This is what I've heard from several people who downloaded it.
