### ISSUE TITLE
Upvoting pin hides it from "Local Places"

### ISSUE THREAD

**Issue by ryansama** [fridayideas/daytomato#121]
To replicate: 
1. Go to Local Places
2. Upvote a pin
3. Close Local Places and open it again

It could be that our query that sorts these pins are a bit off (my understanding is that the most up voted pins appear at the top). I modified a pin to have `likes` at `-5` and it appeared at the top, so perhaps we're sorting them in increasing order.

**Comment by ToucheSir** [comment]
The places view currently sorts by ascending number of votes. Will tackle this ASAP.
