### ISSUE TITLE
Users should be able to delete their pin

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomato#19]

**Comment by james-woo** [comment]
- Learn recyclerview, viewadapters, viewholders, android cards, and the ViewPin activity
- You can add a dropdown menu to each "card" (the viewholder)
- Add delete as one of the menu options
- Delete only if the pin is owned by the user

**Comment by james-woo** [comment]
Zane was working on this!

**Comment by ryansama** [comment]
@Zanelib1 you can assign an issue to yourself on the right under "Assignees"
