### ISSUE TITLE
Refresh page when user moves screen

### ISSUE THREAD

**Issue by ToucheSir** [fridayideas/daytomato#3]
Get user's screen size, estimate top left coordinate, bottom right coordinate, and only grab pins within that constraint

**Comment by james-woo** [comment]
Get user's screen size, estimate top left coordinate, bottom right coordinate, and only grab pins within that constraint

**Comment by james-woo** [comment]
Instead of refreshing the page every time the screen moves, which proved to be incredibly difficult, we should in the future, split the data into cities. e.g. Victoria Table, Vancouver Table, etc. which should solve the problem of loading too much data (good thing we won't have too much data)
