### ISSUE TITLE
Make pins with our custom icons

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomato#30]
The pins that are placed should now use our custom pins

**Comment by alixvoor** [comment]
roughly what we need to do:
class OwnIconRendered extends DefaultClusterRenderer<MyItem> {
    public OwnIconRendered(Context context, GoogleMap map,
                           ClusterManager<MyItem> clusterManager) {
        super(context, map, clusterManager);
    }
    @Override
    protected void onBeforeClusterItemRendered(MyItem item, MarkerOptions markerOptions) {
        markerOptions.icon(BitmapDescriptorFactory.fromResource(R.drawable.2-tomatoPin);
        super.onBeforeClusterItemRendered(item, markerOptions);
    }
}

and then in MapFragment.cs when we call clustermanager set the icon using:
mClusterManager.setRenderer(new OwnIconRendered(activity.getApplicationContext(), getMap(), mClusterManager));

Java solution here: http://stackoverflow.com/questions/27745299/how-to-add-title-snippet-and-icon-to-clusteritem/27745681#27745681

**Comment by alixvoor** [comment]
This actually looks more like what we need:

protected override void OnElementPropertyChanged (object sender, PropertyChangedEventArgs e)
{
  base.OnElementPropertyChanged (sender, e);
  if (e.PropertyName.Equals ("VisibleRegion") && !isDrawn) {
    map.Clear ();
    foreach (var pin in customPins) {
      var marker = new MarkerOptions ();
      marker.SetPosition (new LatLng (pin.Pin.Position.Latitude, pin.Pin.Position.Longitude));
      marker.SetTitle (pin.Pin.Label);
      marker.SetSnippet (pin.Pin.Address);
      marker.SetIcon (BitmapDescriptorFactory.FromResource (Resource.Drawable.pin));

      map.AddMarker (marker);
    }
    isDrawn = true;
  }
}

Found 3/4's of the way down this page: https://developer.xamarin.com/guides/xamarin-forms/custom-renderer/map/
