### ISSUE TITLE
User authentication client code

### ISSUE THREAD

**Issue by ryansama** [fridayideas/daytomato#33]
- user authentication, sending requests to server to create a new account

**Comment by james-woo** [comment]
Should also get the users profile picture, if you can, and create a local database to store their profile picture

**Comment by ryansama** [comment]
It is definitely possible to get the profile picture with the Xamarin.Auth login method: 

`{
10-06 17:25:53.873 I/mono-stdout( 4456):  "id": "111337114679371954122",
 "id": "111337114679371954122",
 "email": "ryan.samarajeewa@gmail.com",
 "verified_email": true,
 "name": "Ryan Samarajeewa",
 "given_name": "Ryan",
 "family_name": "Samarajeewa",
 "link": "https://plus.google.com/+RyanSamarajeewa",
 "picture": "https://lh4.googleusercontent.com/-sbjNkIkzn38/AAAAAAAAAAI/AAAAAAAACwM/HtspGQpBs_o/photo.jpg"
}`

**Comment by ryansama** [comment]
Need to tweak DayTomatoClient to work with future server-side updates.

**Comment by alexeyza** [comment]
Are you using (or planning to use) any OAuth?

**Comment by ToucheSir** [comment]
We are currently using oauth/openid connect exclusively for authentication.
