### ISSUE TITLE
Add seed logic

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomato#39]
- [ ] When user creates a pin, add some seeds
- [ ] When user has their pin liked/disliked, update their seeds
- [ ]  When user is within the vicinity of a pin (maybe 300 yards) and taps on it, add some seeds to all the users who own that pin

**Comment by alixvoor** [comment]
Got the first bullet to work internally (create a pin and add a seed), once we have accounts working we will have to update the number of seeds and pins for that account as well. Not sure if we can do the other bullets for this issue until we have accounts working.
