### ISSUE TITLE
Unify Coordinate data structure on client and server

### ISSUE THREAD

**Issue by ToucheSir** [fridayideas/daytomato#73]
Currently, the server and db store latitude and longitude on a pin as part of a nested coordinate field. However, the client elects to flatten out this structure, electing to directly place latitude and longitude on the pin itself. To minimize the hassle of converting between both formats, we should consider restructuring either client or server so that the format and structure of the data is consistent.

**Comment by ryansama** [comment]
Is this whats causing the crash?

**Comment by ToucheSir** [comment]
Not exactly, but since the crash was contained in the model deserialization code, this would help greatly towards cleaning that up.
