### ISSUE TITLE
Catch empty field exceptions

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomato#77]
Should probably sweep the app to catch places where there are fields being entered so it doesn't crash

**Comment by ToucheSir** [comment]
We should look into implementing native Android form validation before resorting to patching over exceptions :)

**Comment by ryansama** [comment]
Yeah, something like [this](http://www.androidhive.info/wp-content/uploads/2015/09/android-material-design-floating-labels-error-messages.png) would be great

**Comment by ToucheSir** [comment]
Perhaps we can leverage [setError](http://stacktips.com/tutorials/android/edittext-validation-in-android-example) with something like [FluentValidation](https://github.com/JeremySkinner/FluentValidation)?
